# SPDX-FileCopyrightText: Dom Rodriguez <shymega+toybox@shymega.org.uk>
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "steam-toybox"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
diesel = { version = "2.0.4", features = ["sqlite"] }
env_logger = "0.10.0"
futures = "0.3.28"
iced = "0.9.0"
libsqlite3-sys = { version = "0.26.0", features = ["bundled"] }
log = "0.4.17"
rhai = "1.14.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
