# SPDX-FileCopyrightText: 2023 The Steam-ToyBox Developers
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "steam-toybox"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
diesel = { version = "2.1.0", features = ["sqlite"] }
env_logger = "0.10.0"
futures = "0.3.28"
iced = "0.10.0"
libsqlite3-sys = { version = "0.26.0", features = ["bundled"] }
log = "0.4.20"
rhai = "1.15.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
thiserror = "1.0.47"
tokio = { version = "1.32.0", features = ["full"] }
