# SPDX-FileCopyrightText: 2023 The Steam-ToyBox Developers
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "steam-toybox"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stoybox"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.75"
diesel = { version = "2.1.1", features = ["sqlite"] }
env_logger = "0.10.0"
futures = "0.3.28"
ge-man = "0.1.2"
iced = "0.10.0"
libsqlite3-sys = { version = "0.26.0", features = ["bundled"] }
log = "0.4.20"
openssl = { version = "0.10.57", features = ["vendored"] }
proton-call = "3.1.2"
rhai = "1.16.2"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
steamid-ng = "1.0.0"
steamlocate = { version = "1.2.1", features = ["steamid_ng"] }
steamworks = { version = "0.10.0", features = ["serde"] }
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["full"] }
