---
name: Nightly builder for Linux

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-nightlies-linux:
    name: Nightly builds for Linux (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache Rust assets
        id: rust-cache
        uses: Swatinem/rust-cache@v2
      - name: Configure Rust
        if: ${{ steps.rust-cache.outputs.cache-hit != 'true' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.72.1
          default: true
          components: llvm-tools-preview
          override: true
          target: ${{ matrix.target }}
          profile: minimal
      - name: Install Cross
        if: ${{ steps.rust-cache.outputs.cache-hit != 'true' }}
        uses: brndnmtthws/rust-action-cargo-binstall@v1.0.1
        with:
          packages: cross
      - name: Build for ${{ matrix.target }}
        id: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: >-
            --all --locked --verbose --target=${{ matrix.target }}
          use-cross: true
      - name: Zip up the artifacts
        id: zipup
        if: ${{ steps.build.outcome == 'success' }}
        run: zip ${{ github.workspace }}/steam-toybox-nightly-${{ matrix.target }}.zip ${{ github.workspace }}/target/${{ matrix.target }}/debug/stoybox
      - name: Create nightly release
        continue-on-error: true
        if: ${{ steps.zipup.outcome == 'success' }}
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: true
          body: "Nightly build of `Steam-ToyBox` for target: ${{ matrix.target }}"
          release_name: steam-toybox-nightly-${{ matrix.target }}
          tag_name: steam-toybox-nightly-${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload debug nightly build
        run: gh release upload steam-toybox-nightly-${{ matrix.target }} ${{ github.workspace }}/steam-toybox-nightly-${{ matrix.target }}.zip -clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
