# SPDX-FileCopyrightText: 2023 The Steam-ToyBox Developers
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
name: Nightly builder for macOS

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-nightlies-mac:
    name: Nightly builds for macOS (x86_64-apple-darwin)
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.1.1
      - name: Cache Rust assets
        id: rust-cache
        uses: Swatinem/rust-cache@v2
      - name: Configure Rust
        if: ${{ steps.rust-cache.outputs.cache-hit != 'true' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.72.1
          default: true
          components: llvm-tools-preview
          override: true
          target: x86_64-apple-darwin
          profile: minimal
      - name: Build for x86_64-apple-darwin
        id: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: >-
            --all --locked --verbose --target=x86_64-apple-darwin
      - name: Zip up the artifacts
        id: zipup
        if: ${{ steps.build.outcome == 'success' }}
        run: zip ${{ github.workspace }}/steam-toybox-nightly-x86_64-apple-darwin.zip ${{ github.workspace }}/target/x86_64-apple-darwin/debug/stoybox
      - name: Create nightly release
        continue-on-error: true
        if: ${{ steps.zipup.outcome == 'success' }}
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: true
          body: "Nightly build of `Steam-ToyBox` for target: x86_64-apple-darwin"
          release_name: steam-toybox-nightly-x86_64-apple-darwin
          tag_name: steam-toybox-nightly-x86_64-apple-darwin
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload debug nightly build
        run: gh release upload steam-toybox-nightly-x86_64-apple-darwin ${{ github.workspace }}/steam-toybox-nightly-x86_64-apple-darwin.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
