# SPDX-FileCopyrightText: 2023 The Steam-ToyBox Developers
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
name: Nix packaging tests

on:
  workflow_call:

jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: cachix/install-nix-action@v20
      - name: Check Nix Flake
        run: nix flake check --print-build-logs

  check-nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: cachix/install-nix-action@v20
      - name: Build package
        run: nix build --print-build-logs
