# SPDX-FileCopyrightText: 2023 The Steam-ToyBox Developers
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
name: Release builder for macOS

on:
  workflow_run:
    workflows: [CI test workflow]
    types: [completed]
    branches: [main]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
jobs:
  create-gh-release:
    name: Create release on GitHub.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Create release
        uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-release:
    needs: [create-gh-release]
    name: Release uploader for macOS builds
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache Rust assets
        id: rust-cache
        uses: Swatinem/rust-cache@v2
      - name: Configure Rust
        if: ${{ steps.rust-cache.outputs.cache-hit != 'true' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.72.1
          default: true
          components: llvm-tools-preview
          override: true
          target: x86_64-apple-darwin
          profile: minimal
      - name: Build & upload Steam-ToyBox on GH Releases
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: stoybox
          target: x86_64-apple-darwin
          token: ${{ secrets.GITHUB_TOKEN }}
          archive: steam-toybox-${{ github.ref_name }}-release-x86_64-apple-darwin
          zip: all
          checksum: sha256
