---
name: CI tests for macOS

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  run-mac-tests:
    name: CI tests for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target: [x86_64-apple-darwin]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache Rust assets
        id: rust-cache
        uses: Swatinem/rust-cache@v2
      - name: Configure Rust
        if: ${{ steps.rust-cache.outputs.cache-hit != 'true' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.72.1
          profile: minimal
          components: clippy,rustfmt
          override: true
          target: ${{ matrix.target }}
          default: true

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target=${{ matrix.target }}

      - name: Run Cargo checks
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target=${{ matrix.target }}

      - name: Run Clippy tests
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target=${{ matrix.target }}
