# SPDX-FileCopyrightText: 2023 The Steam-ToyBox Developers
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
name: CI Tests

on:
  push:
    paths: ["src/**", "Cargo.toml", "Cargo.lock", "rust-toolchain", "*.nix"]
  workflow_dispatch:

jobs:
  test-linux:
    uses: ./.github/workflows/ci-tests-linux.yml
    secrets: inherit

  test-mac:
    uses: ./.github/workflows/ci-tests-mac.yml
    secrets: inherit

  test-nix-pm:
    uses: ./.github/workflows/ci-nix-pm-tests.yml
    secrets: inherit
