# SPDX-FileCopyrightText: 2023 The Steam-ToyBox Developers
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
name: CI tests for macOS

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  run-mac-tests:
    name: CI tests for x86_64-apple-darwin
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache Rust assets
        id: rust-cache
        uses: Swatinem/rust-cache@v2
      - name: Configure Rust
        if: ${{ steps.rust-cache.outputs.cache-hit != 'true' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.72.1
          profile: minimal
          components: clippy,rustfmt
          override: true
          target: x86_64-apple-darwin
          default: true
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target=x86_64-apple-darwin
      - name: Run Cargo checks
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target=x86_64-apple-darwin
      - name: Run Clippy tests
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target=x86_64-apple-darwin
      - name: Run formatting checks
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
